### ISSUE TITLE
Review Groups

### ISSUE THREAD

**Issue by kumkumks** [joisemp/inventory-management-system#80]
Environment:

Request Method: GET
Request URL: http://127.0.0.1:4000/lab/1/groups/

Django Version: 4.2
Python Version: 3.11.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'core.apps.CoreConfig',
 'lab.apps.LabConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template error:
In template C:\Users\kumku\OneDrive\Desktop\inventory-management-system\lab\templates\lab\group-list.html, error at line 49
   no such table: lab_group
   39 :                     </button>
   40 :                 </a>
   41 :             </div>
   42 :         </div>
   43 :     </div>
   44 : </section> 
   45 : 
   46 : <section class="last-section">
   47 :     <div class="container">
   48 :         <div class="group">
   49 :          {% if groups %} 
   50 :         <div class="wrapper">
   51 :             {% for group in groups %}
   52 :             <a href="{% url 'lab:group-detail' lab.pk group.pk%}" class="card-link">
   53 :                 <div class="card"><span><b>{{group.title}}</b></span>
   54 :                 <p>Date create : {{group.date_created}}</p>
   55 :                 </div>
   56 :             </a>
   57 :             {% endfor %}
   58 :         </div>
   59 :         {% else %}

Traceback (most recent call last):
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The above exception (no such table: lab_group) was the direct cause of the following exception:
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\template\defaulttags.py", line 320, in render
    if match:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\models\query.py", line 412, in __bool__
    self._fetch_all()
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumku\OneDrive\Desktop\inventory-management-system\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: OperationalError at /lab/1/groups/
Exception Value: no such table: lab_group

![image](https://github.com/joisemp/inventory-management-system/assets/146065195/cd21e221-1477-49d9-a288-0eb560354f92)

**Comment by joisemp** [comment]
Make sure to stop the server `ctrl+c` and delete folders with name `__pycache__` 
:point_down: 
![image](https://github.com/joisemp/inventory-management-system/assets/69669027/336fa3ff-4b89-497a-b329-beb99018aa1e)

Can you try deleting the database and after making sure the virtual environment is activated run these commands :
- `python manage.py makemigrations`
- `python manage.py migrate`

Now you can see a new database is created. After that : 
- Run the server `python manage.py runserver 'port-address'`
- Register admin
- Add staff
- Try all the other features

**Comment by joisemp** [comment]
All good. Just some migration issue
